// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServer_Interface.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nanomite.Services.Network.Grpc {

  /// <summary>Holder for reflection information generated from GrpcServer_Interface.proto</summary>
  public static partial class GrpcServerInterfaceReflection {

    #region Descriptor
    /// <summary>File descriptor for GrpcServer_Interface.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GrpcServerInterfaceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpHcnBjU2VydmVyX0ludGVyZmFjZS5wcm90bxIeTmFub21pdGUuU2Vydmlj",
            "ZXMuTmV0d29yay5HcnBjGg1Db21tYW5kLnByb3RvGhJGZXRjaFJlcXVlc3Qu",
            "cHJvdG8aEkdycGNSZXNwb25zZS5wcm90bxoRTmV0d29ya1VzZXIucHJvdG8y",
            "vQIKCkdycGNTZXJ2ZXISZAoKT3BlblN0cmVhbRInLk5hbm9taXRlLlNlcnZp",
            "Y2VzLk5ldHdvcmsuR3JwYy5Db21tYW5kGicuTmFub21pdGUuU2VydmljZXMu",
            "TmV0d29yay5HcnBjLkNvbW1hbmQiACgBMAESYgoHRXhlY3V0ZRInLk5hbm9t",
            "aXRlLlNlcnZpY2VzLk5ldHdvcmsuR3JwYy5Db21tYW5kGiwuTmFub21pdGUu",
            "U2VydmljZXMuTmV0d29yay5HcnBjLkdycGNSZXNwb25zZSIAEmUKBUZldGNo",
            "EiwuTmFub21pdGUuU2VydmljZXMuTmV0d29yay5HcnBjLkZldGNoUmVxdWVz",
            "dBosLk5hbm9taXRlLlNlcnZpY2VzLk5ldHdvcmsuR3JwYy5HcnBjUmVzcG9u",
            "c2UiAEIrCg9pby5ncnBjLm1lc3NhZ2VCEE1lc3NhZ2VEYXRhUHJvdG9QAaIC",
            "A0hMV2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Nanomite.Services.Network.Grpc.CommandReflection.Descriptor, global::Nanomite.Services.Network.Grpc.FetchRequestReflection.Descriptor, global::Nanomite.Services.Network.Grpc.GrpcResponseReflection.Descriptor, global::Nanomite.Services.Network.Grpc.NetworkUserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
