// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServer_Interface.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nanomite.Services.Network.Grpc {

  /// <summary>Holder for reflection information generated from GrpcServer_Interface.proto</summary>
  public static partial class GrpcServerInterfaceReflection {

    #region Descriptor
    /// <summary>File descriptor for GrpcServer_Interface.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GrpcServerInterfaceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpHcnBjU2VydmVyX0ludGVyZmFjZS5wcm90bxIeTmFub21pdGUuU2Vydmlj",
            "ZXMuTmV0d29yay5HcnBjGg1Db21tYW5kLnByb3RvGhJGZXRjaFJlcXVlc3Qu",
            "cHJvdG8aEkdycGNSZXNwb25zZS5wcm90bxoRTmV0d29ya1VzZXIucHJvdG8y",
            "pQMKCkdycGNTZXJ2ZXISZgoHQ29ubmVjdBIrLk5hbm9taXRlLlNlcnZpY2Vz",
            "Lk5ldHdvcmsuR3JwYy5OZXR3b3JrVXNlchosLk5hbm9taXRlLlNlcnZpY2Vz",
            "Lk5ldHdvcmsuR3JwYy5HcnBjUmVzcG9uc2UiABJkCgpPcGVuU3RyZWFtEicu",
            "TmFub21pdGUuU2VydmljZXMuTmV0d29yay5HcnBjLkNvbW1hbmQaJy5OYW5v",
            "bWl0ZS5TZXJ2aWNlcy5OZXR3b3JrLkdycGMuQ29tbWFuZCIAKAEwARJiCgdF",
            "eGVjdXRlEicuTmFub21pdGUuU2VydmljZXMuTmV0d29yay5HcnBjLkNvbW1h",
            "bmQaLC5OYW5vbWl0ZS5TZXJ2aWNlcy5OZXR3b3JrLkdycGMuR3JwY1Jlc3Bv",
            "bnNlIgASZQoFRmV0Y2gSLC5OYW5vbWl0ZS5TZXJ2aWNlcy5OZXR3b3JrLkdy",
            "cGMuRmV0Y2hSZXF1ZXN0GiwuTmFub21pdGUuU2VydmljZXMuTmV0d29yay5H",
            "cnBjLkdycGNSZXNwb25zZSIAQisKD2lvLmdycGMubWVzc2FnZUIQTWVzc2Fn",
            "ZURhdGFQcm90b1ABogIDSExXYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Nanomite.Services.Network.Grpc.CommandReflection.Descriptor, global::Nanomite.Services.Network.Grpc.FetchRequestReflection.Descriptor, global::Nanomite.Services.Network.Grpc.GrpcResponseReflection.Descriptor, global::Nanomite.Services.Network.Grpc.NetworkUserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
