// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResultCode.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nanomite.Services.Network.Grpc {

  /// <summary>Holder for reflection information generated from ResultCode.proto</summary>
  public static partial class ResultCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for ResultCode.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResultCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBSZXN1bHRDb2RlLnByb3RvEh5OYW5vbWl0ZS5TZXJ2aWNlcy5OZXR3b3Jr",
            "LkdycGMqHwoKUmVzdWx0Q29kZRIGCgJPSxAAEgkKBUVSUk9SEAFCKwoPaW8u",
            "Z3JwYy5tZXNzYWdlQhBNZXNzYWdlRGF0YVByb3RvUAGiAgNITFdiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Nanomite.Services.Network.Grpc.ResultCode), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ResultCode {
    [pbr::OriginalName("OK")] Ok = 0,
    [pbr::OriginalName("ERROR")] Error = 1,
  }

  #endregion

}

#endregion Designer generated code
