// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommandType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nanomite.Services.Network.Grpc {

  /// <summary>Holder for reflection information generated from CommandType.proto</summary>
  public static partial class CommandTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for CommandType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommandTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFDb21tYW5kVHlwZS5wcm90bxIeTmFub21pdGUuU2VydmljZXMuTmV0d29y",
            "ay5HcnBjKjAKC0NvbW1hbmRUeXBlEgoKBkFjdGlvbhAAEgsKB01lc3NhZ2UQ",
            "ARIICgRGaWxlEAJCKwoPaW8uZ3JwYy5tZXNzYWdlQhBNZXNzYWdlRGF0YVBy",
            "b3RvUAGiAgNITFdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Nanomite.Services.Network.Grpc.CommandType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum CommandType {
    [pbr::OriginalName("Action")] Action = 0,
    [pbr::OriginalName("Message")] Message = 1,
    [pbr::OriginalName("File")] File = 2,
  }

  #endregion

}

#endregion Designer generated code
