// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServer_Interface.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nanomite.Services.Network.Grpc {

  /// <summary>Holder for reflection information generated from GrpcServer_Interface.proto</summary>
  public static partial class GrpcServerInterfaceReflection {

    #region Descriptor
    /// <summary>File descriptor for GrpcServer_Interface.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GrpcServerInterfaceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpHcnBjU2VydmVyX0ludGVyZmFjZS5wcm90bxIeTmFub21pdGUuU2Vydmlj",
            "ZXMuTmV0d29yay5HcnBjGg1Db21tYW5kLnByb3RvGhJGZXRjaFJlcXVlc3Qu",
            "cHJvdG8aEkdycGNSZXNwb25zZS5wcm90bxoRTmV0d29ya1VzZXIucHJvdG8y",
            "pAMKCkdycGNTZXJ2ZXISZQoHQ29ubmVjdBIrLk5hbm9taXRlLlNlcnZpY2Vz",
            "Lk5ldHdvcmsuR3JwYy5OZXR3b3JrVXNlchorLk5hbm9taXRlLlNlcnZpY2Vz",
            "Lk5ldHdvcmsuR3JwYy5OZXR3b3JrVXNlciIAEmQKCk9wZW5TdHJlYW0SJy5O",
            "YW5vbWl0ZS5TZXJ2aWNlcy5OZXR3b3JrLkdycGMuQ29tbWFuZBonLk5hbm9t",
            "aXRlLlNlcnZpY2VzLk5ldHdvcmsuR3JwYy5Db21tYW5kIgAoATABEmIKB0V4",
            "ZWN1dGUSJy5OYW5vbWl0ZS5TZXJ2aWNlcy5OZXR3b3JrLkdycGMuQ29tbWFu",
            "ZBosLk5hbm9taXRlLlNlcnZpY2VzLk5ldHdvcmsuR3JwYy5HcnBjUmVzcG9u",
            "c2UiABJlCgVGZXRjaBIsLk5hbm9taXRlLlNlcnZpY2VzLk5ldHdvcmsuR3Jw",
            "Yy5GZXRjaFJlcXVlc3QaLC5OYW5vbWl0ZS5TZXJ2aWNlcy5OZXR3b3JrLkdy",
            "cGMuR3JwY1Jlc3BvbnNlIgBCKwoPaW8uZ3JwYy5tZXNzYWdlQhBNZXNzYWdl",
            "RGF0YVByb3RvUAGiAgNITFdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Nanomite.Services.Network.Grpc.CommandReflection.Descriptor, global::Nanomite.Services.Network.Grpc.FetchRequestReflection.Descriptor, global::Nanomite.Services.Network.Grpc.GrpcResponseReflection.Descriptor, global::Nanomite.Services.Network.Grpc.NetworkUserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
