// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetworkUser.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nanomite.Services.Network.Grpc {

  /// <summary>Holder for reflection information generated from NetworkUser.proto</summary>
  public static partial class NetworkUserReflection {

    #region Descriptor
    /// <summary>File descriptor for NetworkUser.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NetworkUserReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFOZXR3b3JrVXNlci5wcm90bxIeTmFub21pdGUuU2VydmljZXMuTmV0d29y",
            "ay5HcnBjIlMKC05ldHdvcmtVc2VyEhEKCUxvZ2luTmFtZRgNIAEoCRIUCgxQ",
            "YXNzd29yZEhhc2gYECABKAkSGwoTQXV0aGVudGljYXRpb25Ub2tlbhgRIAEo",
            "CUIrCg9pby5ncnBjLm1lc3NhZ2VCEE1lc3NhZ2VEYXRhUHJvdG9QAaICA0hM",
            "V2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Nanomite.Services.Network.Grpc.NetworkUser), global::Nanomite.Services.Network.Grpc.NetworkUser.Parser, new[]{ "LoginName", "PasswordHash", "AuthenticationToken" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class NetworkUser : pb::IMessage<NetworkUser> {
    private static readonly pb::MessageParser<NetworkUser> _parser = new pb::MessageParser<NetworkUser>(() => new NetworkUser());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NetworkUser> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nanomite.Services.Network.Grpc.NetworkUserReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkUser() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkUser(NetworkUser other) : this() {
      loginName_ = other.loginName_;
      passwordHash_ = other.passwordHash_;
      authenticationToken_ = other.authenticationToken_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkUser Clone() {
      return new NetworkUser(this);
    }

    /// <summary>Field number for the "LoginName" field.</summary>
    public const int LoginNameFieldNumber = 13;
    private string loginName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LoginName {
      get { return loginName_; }
      set {
        loginName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PasswordHash" field.</summary>
    public const int PasswordHashFieldNumber = 16;
    private string passwordHash_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PasswordHash {
      get { return passwordHash_; }
      set {
        passwordHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AuthenticationToken" field.</summary>
    public const int AuthenticationTokenFieldNumber = 17;
    private string authenticationToken_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AuthenticationToken {
      get { return authenticationToken_; }
      set {
        authenticationToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NetworkUser);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NetworkUser other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoginName != other.LoginName) return false;
      if (PasswordHash != other.PasswordHash) return false;
      if (AuthenticationToken != other.AuthenticationToken) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LoginName.Length != 0) hash ^= LoginName.GetHashCode();
      if (PasswordHash.Length != 0) hash ^= PasswordHash.GetHashCode();
      if (AuthenticationToken.Length != 0) hash ^= AuthenticationToken.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LoginName.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(LoginName);
      }
      if (PasswordHash.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(PasswordHash);
      }
      if (AuthenticationToken.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(AuthenticationToken);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LoginName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LoginName);
      }
      if (PasswordHash.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(PasswordHash);
      }
      if (AuthenticationToken.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(AuthenticationToken);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NetworkUser other) {
      if (other == null) {
        return;
      }
      if (other.LoginName.Length != 0) {
        LoginName = other.LoginName;
      }
      if (other.PasswordHash.Length != 0) {
        PasswordHash = other.PasswordHash;
      }
      if (other.AuthenticationToken.Length != 0) {
        AuthenticationToken = other.AuthenticationToken;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 106: {
            LoginName = input.ReadString();
            break;
          }
          case 130: {
            PasswordHash = input.ReadString();
            break;
          }
          case 138: {
            AuthenticationToken = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
