// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServer_Interface.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nanomite.Core.Network.Common {

  /// <summary>Holder for reflection information generated from GrpcServer_Interface.proto</summary>
  public static partial class GrpcServerInterfaceReflection {

    #region Descriptor
    /// <summary>File descriptor for GrpcServer_Interface.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GrpcServerInterfaceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpHcnBjU2VydmVyX0ludGVyZmFjZS5wcm90bxIcTmFub21pdGUuQ29yZS5O",
            "ZXR3b3JrLkNvbW1vbhoNQ29tbWFuZC5wcm90bxoSRmV0Y2hSZXF1ZXN0LnBy",
            "b3RvGhJHcnBjUmVzcG9uc2UucHJvdG8aEU5ldHdvcmtVc2VyLnByb3RvMrEC",
            "CgpHcnBjU2VydmVyEmAKCk9wZW5TdHJlYW0SJS5OYW5vbWl0ZS5Db3JlLk5l",
            "dHdvcmsuQ29tbW9uLkNvbW1hbmQaJS5OYW5vbWl0ZS5Db3JlLk5ldHdvcmsu",
            "Q29tbW9uLkNvbW1hbmQiACgBMAESXgoHRXhlY3V0ZRIlLk5hbm9taXRlLkNv",
            "cmUuTmV0d29yay5Db21tb24uQ29tbWFuZBoqLk5hbm9taXRlLkNvcmUuTmV0",
            "d29yay5Db21tb24uR3JwY1Jlc3BvbnNlIgASYQoFRmV0Y2gSKi5OYW5vbWl0",
            "ZS5Db3JlLk5ldHdvcmsuQ29tbW9uLkZldGNoUmVxdWVzdBoqLk5hbm9taXRl",
            "LkNvcmUuTmV0d29yay5Db21tb24uR3JwY1Jlc3BvbnNlIgBCKwoPaW8uZ3Jw",
            "Yy5tZXNzYWdlQhBNZXNzYWdlRGF0YVByb3RvUAGiAgNITFdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Nanomite.Core.Network.Common.CommandReflection.Descriptor, global::Nanomite.Core.Network.Common.FetchRequestReflection.Descriptor, global::Nanomite.Core.Network.Common.GrpcResponseReflection.Descriptor, global::Nanomite.Core.Network.Common.NetworkUserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
